### ISSUE TITLE
6/site-packages/django_squash/apps.py", line 2, in <module>   from django.db.migrations.serializer import Serializer

### ISSUE THREAD

**Issue by dotcomlatam** [kingbuzzman/django-squash#4]
i try use this package but this error is generated

my implementation use multi tenant, we use docker and it occurs as soon as we start after installing as indicated in the documentation

 Traceback (most recent call last):
File "manage.py", line 30, in <module>
  execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
  utility.execute()
File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
  django.setup()
File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
  apps.populate(settings.INSTALLED_APPS)
File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
  app_config = AppConfig.create(entry)
File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 116, in create
  mod = import_module(mod_path)
File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/usr/local/lib/python3.6/site-packages/django_squash/apps.py", line 2, in <module>
  from django.db.migrations.serializer import Serializer
ImportError: cannot import name 'Serializer'

**Comment by kingbuzzman** [comment]
Hi @dotcomlatam,

What version of django are you using?

**Comment by kingbuzzman** [comment]
@dotcomlatam If you think i closed this incorrectly, and this is not your issue, you're more than welcome to opening it back up, just provide more details. 

Cheers
